In [14]:
import pandas as pd
import numpy as np

In [17]:
sample_data = pd.read_csv('Resources/Data/46_May.csv')
sample_data = sample_data.dropna(how="any")

In [18]:
sample_data.head()

,Index,Date,Unknown,Message,Code,Parameter_from,Parameter_to
2,3,1/5/18 0:04,1,Work Data Change: Wire Length is from 1255 to ...,257,1255.0,1705.0
28,29,1/5/18 1:37,1,Work Data Change: Wire Feed Speed 1 is from 4....,2564,4.0,3.0
29,30,1/5/18 1:37,1,Work Data Change: Wire Feed Speed 2 is from 4....,2565,4.0,10.0
30,31,1/5/18 1:37,1,Work Data Change: Wire Length Correction 2 is ...,2562,0.0,1.7
42,43,1/5/18 1:37,1,Work Data Change: Wire Length is from 1705 to ...,257,1705.0,1675.0

In [4]:
# function to extract only cities from location column
def split_record(info):
    ret_val = info.split(":")[1]
    return ret_val

In [7]:
sample_data[['3','message']] = sample_data['3'].str.split(':',expand=True)
sample_data

KeyError: '3'

In [5]:
sample_data["Description"] = sample_data[3].map(split_record)

In [6]:
sample_data.head()

,0,1,2,3,4,5,6,Description
16,16,30/05/2018 10:42:05,1,Work Data Change: Wire Length Correction 1 is ...,2561,0.0,1.7,Wire Length Correction 1 is from 0.0 to 1.7
17,17,30/05/2018 10:42:05,1,Work Data Change: Wire Length Correction 2 is ...,2562,1.7,0.0,Wire Length Correction 2 is from 1.7 to 0.0
18,18,30/05/2018 10:42:05,1,Work Data Change: Wire Length Correction 3 is ...,2563,0.7,0.0,Wire Length Correction 3 is from 0.7 to 0.0
33,33,30/05/2018 10:42:05,1,Work Data Change: Wire Length is from 440 to 100,257,440.0,100.0,Wire Length is from 440 to 100
34,34,30/05/2018 10:42:05,1,Work Data Change: Strip Length 1 is from 3.7 t...,513,3.7,0.0,Strip Length 1 is from 3.7 to 0.0